spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
#mybatis:
#  mapper-locations: classpath:lee/wedding/api/mapper/*.xml
#  type-aliases-package: lee.wedding.api.mapper.*
#  configuration:
#    map-underscore-to-camel-case: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:
      timeout: 2000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

aliyun:
  apiKey: sk-f0fd0ce6fc904ab3848630035123ec50
  model: qwen-max-latest
